"""add PendingBooking and Booking tables

Revision ID: 001
Revises:
Create Date: 2024-08-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('confirmation_token', sa.String(length=64), nullable=False),
    sa.Column('store_email', sa.String(length=120), nullable=False),
    sa.Column('guest_email', sa.String(length=120), nullable=False),
    sa.Column('guest_name', sa.String(length=200), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('confirmation_token')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_event_id', sa.String(length=200), nullable=False),
    sa.Column('store_email', sa.String(length=120), nullable=False),
    sa.Column('guest_email', sa.String(length=120), nullable=False),
    sa.Column('guest_name', sa.String(length=200), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    op.drop_table('pending_booking')
    # ### end Alembic commands ###
